Experimental one script release

diff --git a/hostapd-statistics/usr/bin/hostapd-statistics b/hostapd-statistics/usr/bin/hostapd-statistics
--- a/hostapd-statistics/usr/bin/hostapd-statistics
+++ b/hostapd-statistics/usr/bin/hostapd-statistics
@@ -1,9 +1,7 @@
 #!/bin/bash
-#This bash script generates the HTML page on the fly.
-#Since we use socat, we don't need dependencies to real webservers like apache. Also, it is nearly impossible to exploit this. (I hope..)
+#This script simply waits for stuff from Hostapd to appear in the syslog
 # uncomment to debug
 #set -x
-str_trim() { sed -r -e 's,^\s+,,' -e 's,\s+$,,' -e 's,\s+, ,g' "$@"; } # stolen from dywi
 loadcfg() {
 #if we got no conf file define everything here.
 wlandev="wlan0"
@@ -21,6 +19,100 @@ SCRIPT_DIR="${SCRIPT_FILE%/*}"
 source "/etc/hostapd-statistics/CONFIG"
 }
 loadcfg
+timeoutcheck() {
+# This function removes devices which aren't connected anymore but also don't disconnect properly.
+# It uses the iw tool to dump all connected clients.
+while read -r line
+do
+	mac=`echo "$line" | cut -d";" -f1 | tr [:lower:] [:upper:]`
+	iwcheck=`iw dev "$wlandev" station dump | tr [:lower:] [:upper:] |grep -i "$mac"` 
+	if [ -z "$iwcheck" ]; then
+		sed -i -e "/$mac/d" "/dev/shm/conclients" #remove the line with $mac from conclients
+		echo "$mac timed out."
+	fi
+done < "/dev/shm/conclients"
+}
+timeoutcheck_loop() { timeoutcheck; while sleep "$sleeptime"; do timeoutcheck; done; }
+disconnect() {
+	mac=`echo $disconnected | cut -d" " -f8`
+	sed -i -e "/$mac/d" "/dev/shm/conclients"
+	echo "$mac removed from connected clients."
+}
+connect () {
+	mac=`echo $connected | cut -d" " -f8 | tr [:lower:] [:upper:]`
+	echo "Looks like somebody says hello.."
+	unique
+	#check if the mac is already in our list of connected clients
+	alreadythere=`grep $mac "/dev/shm/conclients"`
+	if [ -z "$alreadythere" ]; then
+		iplookup
+		hostname=`nslookup "$ip" | grep "name" | cut -d"=" -f2 | tr -d ' '` 
+		time=`date +"%H:%M"`
+		write="$mac;$ip;$hostname;$time"
+		echo "Client $mac added."
+		echo "$write" >> "/dev/shm/conclients"
+	else
+		echo "Wait, he is already in our Database.."
+	fi
+
+}
+unique() {
+	if ! grep -q "$mac" "/etc/hostapd-statistics/uniquemacs" ; then
+		echo "$mac" >> "/etc/hostapd-statistics/uniquemacs"
+		echo "New device connected. Mac: $mac"
+	fi
+}
+iplookup() {
+	#Find out the corresponding IP to the mac adress
+	ip=`grep "$mac" /proc/net/arp | cut -d" " -f1`
+	#for devices like my sgs2: find out the ip with arp-scan or nmap since it doesn't appear in the arp cache
+	trys=0
+	if [ -z "$ip" ]; then
+		arp-scanlookup
+	fi
+	arp-scanfailcheck
+}
+nmaplookup() {
+	echo "IP lookup with nmap.."
+	ip=`nmap -sP "${dhcpserverip}"/24 | sed -n '/Nmap scan report for/{s/.* //;s/[)(]//g;h};/'"$mac"'/{x;p;q;}'` #thank you sluggr 	
+##sed on freenode
+}
+arp-scanlookup() {
+	echo "IP lookup with arp-scan.."
+	ip=`arp-scan -l -I "$arp_scan_dev" | grep -i "$mac" | head -n1 |grep -E -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'`
+}
+failcheck() {
+	if [ -z "$ip" ]; then
+		trys=$((trys+1))
+		if (( trys < 3 )); then
+			echo "Whoops, nmap ip lookup failed. Try again.."
+			nmaplookup
+			failcheck
+		else
+			echo "Looks like $mac disappeared from the network."
+			exit 0
+		fi
+	fi
+
+
+}
+arp-scanfailcheck() {
+	if [ -z "$ip" ]; then
+		trys=$((trys+1))
+		if (( trys < 3 )); then
+			echo "Whoops, arp-scan ip lookup failed. Try again.."
+			arp-scanlookup
+			arp-scanfailcheck
+		else
+			trys=0
+		echo "Okay.. lets try nmap."
+		nmaplookup
+		failcheck
+	fi
+fi
+
+
+}
 tablecontentgen() {
 while read -r line # cycle through all lines in conclients (flatfile ftw!) and parse the values so they fit into our html page
 do
@@ -133,8 +225,58 @@ if  (( ${use_vnstat} == 1 )); then
 
 }
 
+#onto the real functions
+
+main() {
+
+	echo "Hostapd-statistics launched"
+	# Remove all old entrys and create the file if it doesn't exist.
+	> "/dev/shm/conclients"
+	# Launch the webinterface listener.
+	socat TCP4-LISTEN:"$webinterfaceport",fork,reuseaddr EXEC:"bash /usr/bin/hostapd-statistics web" & 
+	# Run the infinite loop
+	timeoutcheck_loop &
+	readonly TIMEOUTCHECK_PID=$!
+	trap "kill ${TIMEOUTCHECK_PID}; rm '/dev/shm/hostapd_statistics_webradio.pid' > /dev/null 2>&1; rm /dev/shm/conclients " TERM EXIT
+	echo "Adding devices which are already connected.."
+	initialdevices=`iw dev "$wlandev" station dump | sed -e "s/Station/;/g" | grep ";" | cut -d" " -f2`
+	for item in $initialdevices
+	do
+		mac=`echo $item | tr [:lower:] [:upper:]`
+		unique
+		iplookup
+		hostname=`nslookup "$ip" | grep "name" | cut -d"=" -f2 | tr -d ' '` 
+		time=`date +"%H:%M"`
+		write="$mac;$ip;$hostname;$time"
+		echo "Client $mac added."
+		echo "$write" >> "/dev/shm/conclients"
+	done 
+	
+	# The whole watch the syslog thingy
+	while :
+	do
+		inotifywait -q -q -e modify /var/log/syslog && bash "/usr/bin/hostapd-statistics core"
+	done
+}
 
 
+
+
+core() {
+	isthisimportant=`tail -1 /var/log/syslog | grep "hostapd"`
+	if [ -n "$isthisimportant" ]; then
+		connected=`echo "$isthisimportant" | grep "handshake"`
+		disconnected=`echo "$isthisimportant" | grep "deauthenticated"`
+		if [ -n "$connected" ]; then
+			connect
+		elif [ -n "$disconnected" ]; then
+			disconnect
+		fi
+	
+	fi
+}
+
+web() {
 
 if  (( ${webradio} == 1 )); then
 	#Images
@@ -268,3 +410,26 @@ case  "$request"  in
 		
 		;;
 esac
+
+}
+
+
+
+
+
+
+#teh real script
+case  "$1"  in
+		"web")
+		web
+		;;
+		"core")
+		core
+		;;
+		*)       
+		main
+		;;
+
+
+
+
